package protocol

const (
	E_MT2SRV_TAR_CENTER_SRV   = 0 // 到中心服消息
	E_MT2SRV_TAR_SCENE_SRV    = 1 // 到场景服消息
	E_MT2SRV_TAR_DB_PROXY_SRV = 2 // 到数据库消息
)

const (
	// 1-20 (center server)
	E_MT2SRV_MSG_REQ_KICK_PLAYER    = 0
	E_MT2SRV_MSG_REQ_QUERY_PLAYERS  = 1
	E_MT2SRV_MSG_REQ_GEN_ACTIVE_KEY = 2
	E_MT2SRV_MSG_REQ_LOAD_PLAYER    = 4
	E_MT2SRV_MSG_REQ_REFRESH_PLAYER = 5
	E_MT2SRV_CENTER_MAX             = 20 //最大值
	// 21-50 (scene server)
	E_MT2SRV_MSG_REQ_GM_CMD        = 21
	E_MT2SRV_MSG_REQ_SEND_LETTER   = 22
	E_MT2SRV_MSG_REQ_PEEK_PLAYER   = 23
	E_MT2SRV_MSG_REQ_SEND_SYS_MSG  = 24
	E_MT2SRV_MSG_REQ_BLOCK_ACCT    = 25
	E_MT2SRV_MSG_REQ_BLOCK_DEVICE  = 26
	E_MT2SRV_MSG_REQ_ROLE_SILENT   = 27
	E_MT2SRV_MSG_REQ_ROLE_UNSILENT = 28
	E_MT2SRV_MSG_REQ_UPDATE_CONFIG = 29
	E_MT2SRV_SCENE_MAX             = 50 //最大值

	// 51-70 (db server)
	E_MT2SRV_MSG_REQ_SQL_QUERY = 51
	E_MT2SRV_DB_MAX            = 70 //最大值

	// 100-150 (维护)
	E_MT2SRV_MSG_MONITOR_MIN   = 100
	E_MT2SRV_MSG_MONITOR_STATE = 100
	E_MT2SRV_MSG_MONITOR_QUIT  = 101
	E_MT2SRV_MSG_MONITOR_OPEN  = 102
	E_MT2SRV_MSG_MONITOR_MAX   = 150
)

const (
	// 1-20 (center server)
	E_SRV2MT_MSG_ACK_KICK_PLAYER       = 0
	E_SRV2MT_MSG_ACK_QUERY_PLAYERS     = 1
	E_SRV2MT_MSG_ACK_GEN_ACTIVE_KEY    = 2
	E_SRV2MT_MSG_REQ_ERROR             = 3
	E_SRV2MT_MSG_ACK_LOAD_PLAYER       = 4
	E_SRV2MT_MSG_ACK_REFRESH_PLAYER    = 5
	E_SRV2MT_MSG_ACK_REFRESH_PLAYER_DB = 6
	// 21-50 (scene server)
	E_SRV2MT_MSG_SCENE_MSG = 21
	// 51-70 (db server)
	E_SRV2MT_MSG_ACK_SQL_QUERY = 51
	// 100-150 (维护)
	E_SRV2MT_MSG_MONITOR_MIN   = 100
	E_SRV2MT_MSG_MONITOR_STATE = 100
	E_SRV2MT_MSG_MONITOR_QUIT  = 101
	E_SRV2MT_MSG_MONITOR_OPEN  = 102
	E_SRV2MT_MSG_MONITOR_MAX   = 150
)

const (
	LOGIC_MESSAGE  = 1 // 逻辑处理
	SEND_TO_SCENE  = 0 // 发送给场景
	SEND_TO_PLAYER = 1 // 发送给玩家
)
